export { default as Room } from './Room'
export { default as CustomSlider } from './CustomSlider'
export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as PieChartComponent } from './Charts/PieChartComponent'
